server:
  port: 8081
spring:
  application:
    name: SkyKaoHe
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SkyKaoHe?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

